[production]
ruralindiaonline.org

[qa]
54.255.193.26

[staging]
ec2-13-58-83-216.us-east-2.compute.amazonaws.com

[vagrant]
development.ruralindiaonline.org

[qa:vars]
git_revision_to_pull=release-candidate

[vagrant:vars]
base_path=/vagrant
app_path=/vagrant
requirements_file="/vagrant/requirements.dev.txt"
settings_path="pari.settings.dev"