[production]
ruralindiaonline.org

[qa]
54.255.193.26

[local]
127.0.0.1

[staging]
ec2-52-14-252-14.us-east-2.compute.amazonaws.com
private_key_file="../pari-test.pem"


[vagrant]
development.ruralindiaonline.org

[production:vars]
git_revision_to_pull=release

[qa:vars]
git_revision_to_pull=release-candidate

[vagrant:vars]
base_path=/vagrant
app_path=/vagrant
requirements_file="/vagrant/requirements.dev.txt"
settings_path="pari.settings.dev"