[production]
ruralindiaonline.org

[staging]
staging.ruralindiaonline.org

[local]
127.0.0.1

[vagrant]
development.ruralindiaonline.org

[production:vars]
git_revision_to_pull=release
allow_robots=True

[staging:vars]
git_revision_to_pull=release-candidate
settings_path="pari.settings.staging"

[vagrant:vars]
base_path=/vagrant
app_path=/vagrant
requirements_file="/vagrant/requirements.dev.txt"
settings_path="pari.settings.dev"

[prod-recovery:vars]
base_path=/vagrant
app_path=/vagrant
requirements_file="/vagrant/requirements.dev.txt"
settings_path="pari.settings.dev"
