---
- name: Install and deploy PARI
  hosts:
    - production
    - qa
    - local
    - staging
    - vagrant
  roles:
    - common
    - nginx
    - postgres
    - elasticsearch
    - django
    - { role: development, when: is_local_development }
