---
- name: Download elasticsearch
  get_url: >
    url=https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-1.7.2.deb
    dest=/tmp/elasticsearch.deb
  become: true
  become_method: sudo
  tags:
    - install
    - restore

- name: Install elasticsearch
  apt: deb=/tmp/elasticsearch.deb
  become: true
  become_method: sudo
  tags:
    - install
    - restore

- name: Restart elasticsearch
  service: name=elasticsearch state=restarted
  become: true
  become_method: sudo
  tags:
    - install
    - restore
